version: "3.3"

services:
    wechat-box-wcferry:
        image: "henryxiaoyang/wechat-box-wcferry:latest"
        restart: unless-stopped
        container_name: "wechat-box-wcferry"
        environment:
            WC_AUTO_RESTART: "yes"
        ports:
            - "8080:8080"
        volumes:
              - "wechat-box-WeChatFiles:/home/app/WeChat Files/"
        tty: true